In [24]:
import torch

tensorA_2x3 = torch.tensor(
    [[1,2,3],
     [3,2,1]]
)

tensorB_1x3 = torch.tensor(
    [[1,2,3]]
)

tensorC_scalar = 5

tensorD_2x1 = torch.tensor(
    [[2],
     [3]]
)

tensorE_3x1 = torch.tensor(
    [[2],
     [3],
     [4]]
)

tensorF_3x2 = torch.tensor(
    [[1,2],
     [3,4],
     [5,6]]
)

tensorG_2x3x2 = torch.tensor(
    [[[1,2],
      [3,4],
      [2,1]],
     [[4,5],
      [5,4],
      [1,2]]]
)

tensorH_2x2x3 = torch.tensor(
    [[[1,2,3],
      [3,2,1]],
     [[4,5,6],
      [6,5,4]]]
)

In [8]:
# *乘，shape相同，对应元素相乘
print(tensorA_2x3 * tensorA_2x3)

tensor([[1, 4, 9],
        [9, 4, 1]])


In [10]:
# *乘，两元素shape不同
print(tensorA_2x3 * tensorB_1x3)
print(tensorA_2x3 * tensorD_2x1)

tensor([[1, 4, 9],
        [3, 4, 3]])
tensor([[2, 4, 6],
        [9, 6, 3]])


In [15]:
# torch.mul()，shape相同，对应元素相乘
print(torch.mul(tensorA_2x3,tensorA_2x3))

tensor([[1, 4, 9],
        [9, 4, 1]])


In [16]:
# torch.mul()，两元素shape不同
print(torch.mul(tensorA_2x3, tensorB_1x3))
print(torch.mul(tensorA_2x3, tensorD_2x1))

tensor([[1, 4, 9],
        [3, 4, 3]])
tensor([[2, 4, 6],
        [9, 6, 3]])


In [18]:
## *乘和torch.mul()方法一致，支持broadcast操作。任意一维得相同或者都相同，例如2x3矩阵能够和2*n、n*3以及2*3的矩阵做*乘、torch.mul()操作

In [22]:
# torch.mm(),二维矩阵乘法,不支持broadcast操作，实现的是数学中的矩阵乘法
print(torch.mm(tensorA_2x3, tensorF_3x2))

tensor([[22, 28],
        [14, 20]])


In [25]:
# torch.bmm()，三维矩阵乘法，b表示的是batch，要求两个矩阵都是三维矩阵,mini-batch训练的时候可能会用到
print(torch.bmm(tensorH_2x2x3, tensorG_2x3x2))

tensor([[[13, 13],
         [11, 15]],

        [[47, 52],
         [53, 58]]])


In [29]:
#torch.matmul()，支持broadcast的矩阵乘法
# a*b*c c*n
print(torch.matmul(tensorH_2x2x3, tensorF_3x2))

tensor([[[ 1,  4,  9],
         [ 9,  4,  1]],

        [[ 4, 10, 18],
         [18, 10,  4]]])


tensor([[[ 7,  6,  5],
         [15, 14, 13],
         [23, 22, 21]],

        [[16, 15, 14],
         [36, 35, 34],
         [56, 55, 54]]])
